version: '3.8'
services:
  backend:
    build:
      context: ./knowledge
    container_name: spring-backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/knowledge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=maxi1973
    depends_on:
      - postgres

  frontend:
    build:
      context: ./knowledge-app
    container_name: react-frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maxi1973
      POSTGRES_DB: knowledge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: