version: '3.8'
services:
  backend:
    build:
      context: ./knowledge
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/knowledge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=maxi1973
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./users-app
    container_name: react-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maxi1973
      POSTGRES_DB: knowledge
    ports:
      - "6432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
  
networks:
  app-network: