/*CREATE TABLE knowledge
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content text,
    created_at timestamp,
    title varchar(500) ,
    updated_at timestamp,
    parent_id bigint,
    CONSTRAINT knowledge_pkey PRIMARY KEY (id),
    CONSTRAINT fk_parent FOREIGN KEY (parent_id)
        REFERENCES knowledge (id)
);


CREATE INDEX idx_content
    ON knowledge(content);

CREATE INDEX idx_parent
    ON knowledge(parent_id);

CREATE INDEX idx_title
    ON knowledge(title);

INSERT INTO knowledge (id, content, created_at, title, updated_at)
VALUES (1, NULL, CURRENT_TIMESTAMP, 'root', CURRENT_TIMESTAMP);

UPDATE knowledge set parent_id=1,content = 'root' WHERE id = 1;
SELECT MAX(id) FROM knowledge;*/